python:
  replicaCount: 1
  image:
    repository: harbor.gryffin-uit.site/coursey/python
    tag: "latest"
  service:
    port: 8002
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

php:
  replicaCount: 2
  image:
    repository: harbor.gryffin-uit.site/coursey/php
    tag: "latest"
  service:
    port: 9000
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

nginx:
  replicaCount: 1
  image:
    repository: harbor.gryffin-uit.site/coursey/nginx
    tag: "latest"
  service:
    type: ClusterIP
    ports:
      - name: http
        containerPort: 80
        servicePort: 80
      - name: admin
        containerPort: 8082
        servicePort: 8082
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "500m"

appConfig:
  apiBaseUrl: "https://api.hnblong.site"

frontend:
  replicaCount: 1
  image:
    repository: harbor.gryffin-uit.site/coursey/frontend
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "500m"

ingress:
  enabled: true
  className: "nginx"

  hosts:
    - name: "api"
      host: "api.hnblong.site" # e.g., api.example.com
      serviceName: "nginx-service"
      port: 80

    - name: "admin"
      host: "admin.hnblong.site" # e.g., admin.example.com
      serviceName: "nginx-service"
      port: 8082

    - name: "frontend"
      host: "hnblong.site"
      serviceName: "frontend-service"
      port: 80
