auth:
  rootPassword: "CHANGE_ME_ROOT_PASSWORD"
  database: "docker-php"
  username: "CHANGE_ME_USERNAME"
  password: "CHANGE_ME_PASSWORD"

primary:
  persistence:
    enabled: true
    storageClass: "local-path"
    size: "3Gi"
  initdb:
    scriptsConfigMap: coursey-mysql-initdb
