apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: coursey-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: coursey-frontend
