apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coursey-db-mysql
spec:
  serviceName: "mysql-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "coursey-backend-role"
        
        vault.hashicorp.com/agent-inject-secret-root-pass: "secret/data/coursey/database"
        vault.hashicorp.com/agent-inject-template-root-pass: |
          {{`{{- with secret "secret/data/coursey/database" -}}{{ .Data.data.MYSQL_ROOT_PASSWORD }}{{- end -}}`}}
          
        vault.hashicorp.com/agent-inject-secret-db-name: "secret/data/coursey/database"
        vault.hashicorp.com/agent-inject-template-db-name: |
          {{`{{- with secret "secret/data/coursey/database" -}}{{ .Data.data.MYSQL_DATABASE }}{{- end -}}`}}
          
        vault.hashicorp.com/agent-inject-secret-db-user: "secret/data/coursey/database"
        vault.hashicorp.com/agent-inject-template-db-user: |
          {{`{{- with secret "secret/data/coursey/database" -}}{{ .Data.data.MYSQL_USER }}{{- end -}}`}}
          
        vault.hashicorp.com/agent-inject-secret-db-pass: "secret/data/coursey/database"
        vault.hashicorp.com/agent-inject-template-db-pass: |
          {{`{{- with secret "secret/data/coursey/database" -}}{{ .Data.data.MYSQL_PASSWORD }}{{- end -}}`}}
          
    spec:
      serviceAccountName: coursey-backend-sa

      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD_FILE
          value: "/vault/secrets/root-pass"
        - name: MYSQL_DATABASE_FILE
          value: "/vault/secrets/db-name"
        - name: MYSQL_USER_FILE
          value: "/vault/secrets/db-user"
        - name: MYSQL_PASSWORD_FILE
          value: "/vault/secrets/db-pass"
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-scripts
        configMap:
          name: coursey-mysql-initdb

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 3Gi