
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coursey-php
  labels:
    app: coursey-php
spec:
  replicas: {{ .Values.php.replicaCount }}
  selector:
    matchLabels:
      app: coursey-php
  template:
    metadata:
      labels:
        app: coursey-php
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "coursey-backend-role"
        vault.hashicorp.com/agent-inject-secret-db-creds: "secret/data/coursey/database"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{`{{- with secret "secret/data/coursey/database" -}}`}}
          export MYSQL_HOST="{{`{{ .Data.data.MYSQL_HOST }}`}}"
          export MYSQL_USER="{{`{{ .Data.data.MYSQL_USER }}`}}"
          export MYSQL_PASSWORD="{{`{{ .Data.data.MYSQL_PASSWORD }}`}}"
          export MYSQL_DATABASE="{{`{{ .Data.data.MYSQL_DATABASE }}`}}"
          export MAIL_USERNAME="{{`{{ .Data.data.MAIL_USERNAME }}`}}"
          export PASS_APP="{{`{{ .Data.data.PASS_APP }}`}}"
          export HOST_NAME="{{`{{ .Data.data.HOST_NAME }}`}}"
          {{`{{- end -}}`}}
    spec:
      serviceAccountName: coursey-backend-sa
      imagePullSecrets:
      - name: harbor-pull-secret
      containers:
      - name: php-fpm
        image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}"  
        command: ["/bin/sh", "-c"]
        args: ["source /vault/secrets/db-creds && php-fpm"]
        ports:
        - containerPort: {{ .Values.php.service.port }}
          name: php-fpm
        resources:
          {{- toYaml .Values.php.resources | nindent 10 }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.php.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 5