name: Coursey CI/CD Pipeline

on:
    push:
        branches:
            - main
            - master
    workflow_dispatch:
        inputs:
            force_build_all:
                description: "Force build all services"
                required: true
                type: boolean
                default: false

jobs:
    sonarqube-analysis:
        name: SonarQube Scan & Quality Gate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Scan Code
              uses: SonarSource/sonarqube-scan-action@v6
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

            # - name: Check Quality Gate
            #   uses: SonarSource/sonarqube-quality-gate-action@v1
            #   timeout-minutes: 5
            #   env:
            #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    detect-changes:
        needs: sonarqube-analysis # Run after SonarQube Analyze
        runs-on: ubuntu-latest
        outputs:
            mysql: ${{ steps.filter.outputs.mysql }}
            nginx: ${{ steps.filter.outputs.nginx }}
            php: ${{ steps.filter.outputs.php }}
            python: ${{ steps.filter.outputs.python }}
            frontend: ${{ steps.filter.outputs.frontend }}
        steps:
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                  filters: |
                      nginx:
                        - 'back-end/nginx/**'
                      php:
                        - 'back-end/php/**'
                      python:
                        - 'back-end/python/**'
                      frontend:
                        - 'front-end/**'

    build-nginx:
        needs: detect-changes
        if: ${{ needs.detect-changes.outputs.nginx == 'true' || inputs.force_build_all == true }}
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - uses: docker/login-action@v3
              with:
                  registry: harbor.gryffin-uit.site
                  username: ${{ secrets.HARBOR_USERNAME }}
                  password: ${{ secrets.HARBOR_PASSWORD }}
            - uses: docker/build-push-action@v5
              with:
                  context: ./back-end
                  file: ./back-end/nginx/Dockerfile
                  push: true
                  tags: |
                      harbor.gryffin-uit.site/coursey/nginx:${{ github.sha }}
                      harbor.gryffin-uit.site/coursey/nginx:latest

    build-php:
        needs: detect-changes
        if: ${{ needs.detect-changes.outputs.php == 'true' || inputs.force_build_all == true }}
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - uses: docker/login-action@v3
              with:
                  registry: harbor.gryffin-uit.site
                  username: ${{ secrets.HARBOR_USERNAME }}
                  password: ${{ secrets.HARBOR_PASSWORD }}
            - uses: docker/build-push-action@v5
              with:
                  context: ./back-end
                  file: ./back-end/php/Dockerfile
                  push: true
                  tags: |
                      harbor.gryffin-uit.site/coursey/php:${{ github.sha }}
                      harbor.gryffin-uit.site/coursey/php:latest

    build-python:
        needs: detect-changes
        if: ${{ needs.detect-changes.outputs.python == 'true' || inputs.force_build_all == true }}
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - uses: docker/login-action@v3
              with:
                  registry: harbor.gryffin-uit.site
                  username: ${{ secrets.HARBOR_USERNAME }}
                  password: ${{ secrets.HARBOR_PASSWORD }}
            - uses: docker/build-push-action@v5
              with:
                  context: ./back-end
                  file: ./back-end/python/Dockerfile
                  push: true
                  tags: |
                      harbor.gryffin-uit.site/coursey/python:${{ github.sha }}
                      harbor.gryffin-uit.site/coursey/python:latest

    build-frontend:
        needs: detect-changes
        if: ${{ needs.detect-changes.outputs.frontend == 'true' || inputs.force_build_all == true }}
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - uses: docker/login-action@v3
              with:
                  registry: harbor.gryffin-uit.site
                  username: ${{ secrets.HARBOR_USERNAME }}
                  password: ${{ secrets.HARBOR_PASSWORD }}
            - uses: docker/build-push-action@v5
              with:
                  context: ./front-end
                  push: true
                  build-args: REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }}
                  tags: |
                      harbor.gryffin-uit.site/coursey/frontend:${{ github.sha }}
                      harbor.gryffin-uit.site/coursey/frontend:latest
